name: Publish Documentation
on:
  push:
    branches:
      - doc/main
  pull_request:
    branches:
      - doc/main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: |
          pip install mkdocs-material
          pip install mdx_truly_sane_lists
      - run: ./build.sh
      - name: Checkout master
        uses: actions/checkout@v3
        with:
          ref: master
          path: main
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - name: Build Blazor application
        shell: pwsh
        run: |
          dotnet publish -c Release -o try main/src/DocoptNet.Playground
          $indexPath = 'try/wwwroot/index.html'
          $index = Get-Content -Raw $indexPath
          $index = $index -replace '(?<=\bbase href=")/(?=")', '/docopt.net/try/'
          Set-Content $indexPath $index -NoNewLine
          Move-Item try/wwwroot site/try
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
