name: Publish Documentation
on:
  push:
    branches:
      - doc/main
  pull_request:
    branches:
      - doc/main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: |
          pip install mkdocs-material
          pip install mdx_truly_sane_lists
      - run: mkdocs build
      - run: |
          for d in v*; do
            cd $d
            mkdocs build -d ../site/$d
            cd ..
          done
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
